### ISSUE TITLE
Engine-q final merge checklist

### ISSUE THREAD

**Issue by jntrnr** [nushell/engine-q#735]
(warning: this list may not be complete, and may have items added as we discover them):

## Commands

- [ ] get (remaining: ...rest)
- [ ] group-by - [andres]
- [ ] merge
- [ ] move
- [ ] save
- [ ] sort-by - [storm]
- [ ] str
- [ ] update cells
- [ ] each window/each group
- [ ] pivot
- [ ] rename
- [ ] split-by - [andres]
- [ ] find
- [ ] post
- [ ] which
- [ ] seq / seq date
- [ ] term size
- [ ] benchmark (remaining: passthrough)
- [ ] ls (remaining: --du flag)
- [ ] default
- [ ] hash
- [ ] load-env
- [ ] detect columns
- [ ] du
- [ ] match (regex type)
- [ ] roll
- [ ] rotate
- [ ] selector
- [ ] headers
- [ ] nu plugin (replaced by "register"?)
- [ ] tutor
- [ ] zip
- [ ] exec
- [ ] format filesize
- [ ] query json

## Features

- [ ] completions for binaries in the PATH/Path
- [ ] finish external completions, `git` as main use case for initial design
- [ ] keybindings file
- [ ] `cd -` (https://github.com/nushell/engine-q/issues/577)
- [ ] `help -s` to search help

## Bugs

- [ ] possible race condition: https://github.com/nushell/engine-q/issues/726
- [ ] entering a file shouldn't be allowed: https://github.com/nushell/engine-q/issues/730
- [ ] `use` + path autocomplete: https://github.com/nushell/engine-q/issues/706
- [ ] zombie plugins: https://github.com/nushell/engine-q/issues/708

**Comment by elferherrera** [comment]
I would add a check for python's virtualenv

**Comment by fdncred** [comment]
This needs to be tweaked an (i think) used to replace the initial issue comments above.

| message                                                                   | e-q resolution                                                        |
| ------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| command [alias] exists but parameter [equals] is missing in eq            | `equals` is not a parameter in engine-q                               |
| command [alias] exists but parameter [rest] is missing in eq              | `reset` renamed to `initial_value`                                    |
| command [all?] exists but parameter [condition] is missing in eq          | `condition` renamed to `predicate`                                    |
| command [ansi gradient] exists but parameter [rest] is missing in eq      | `rest` renamed to `column path` (\* space in param name)              |
| command [ansi strip] exists but parameter [rest] is missing in eq         | `rest` renamed to `column path` (\* space in param name)              |
| command [any?] exists but parameter [condition] is missing in eq          | `condition` renamed to `predicate`                                    |
| command [append] exists but parameter [row value] is missing in eq        | `row value` renamed to `row`                                          |
| command [autoenv trust] with parameter [dir] is missing in eq             | missing                                                               |
| command [autoenv trust] with parameter [quiet] is missing in eq           | missing                                                               |
| command [autoenv untrust] with parameter [dir] is missing in eq           | missing                                                               |
| command [autoenv untrust] with parameter [quiet] is missing in eq         | missing                                                               |
| command [benchmark] exists but parameter [passthrough] is missing in eq   | missing                                                               |
| command [binaryview] with parameter [bytes] is missing in eq              | removed from engine-q                                                 |
| command [binaryview] with parameter [lores] is missing in eq              | removed from engine-q                                                 |
| command [binaryview] with parameter [skip] is missing in eq               | removed from engine-q                                                 |
| command [cd] exists but parameter [directory] is missing in eq            | `directory` renamed to `path`                                         |
| command [chart bar] with parameter [columns] is missing in eq             | missing                                                               |
| command [chart bar] with parameter [format] is missing in eq              | missing                                                               |
| command [chart bar] with parameter [acc] is missing in eq                 | missing                                                               |
| command [chart bar] with parameter [use] is missing in eq                 | missing                                                               |
| command [chart line] with parameter [columns] is missing in eq            | missing                                                               |
| command [chart line] with parameter [format] is missing in eq             | missing                                                               |
| command [chart line] with parameter [acc] is missing in eq                | missing                                                               |
| command [chart line] with parameter [use] is missing in eq                | missing                                                               |
| command [compact] exists but parameter [rest] is missing in eq            | `rest` renamed to `columns`                                           |
| command [config get] with parameter [get] is missing in eq                | removed from engine-q                                                 |
| command [config remove] with parameter [remove] is missing in eq          | removed from engine-q                                                 |
| command [config set] with parameter [key] is missing in eq                | removed from engine-q                                                 |
| command [config set] with parameter [value] is missing in eq              | removed from engine-q                                                 |
| command [config set_into] with parameter [set_into] is missing in eq      | removed from engine-q                                                 |
| command [cp] exists but parameter [src] is missing in eq                  | `src` renamed to `source`                                             |
| command [cp] exists but parameter [dst] is missing in eq                  | `dst` renamed to `destination`                                        |
| command [dfr aggregate] exists but parameter [operation] is missing in eq | `operation` renamed to `operation-name`                               |
| command [dfr append] exists but parameter [axis] is missing in eq         | missing                                                               |
| command [dfr cum] with parameter [type] is missing in eq                  | `cum` renamed to `cumulative`                                         |
| command [dfr cum] with parameter [reverse] is missing in eq               | `cum` renamed to `cumulative`                                         |
| command [dfr drop-duplicates] with parameter [subset] is missing in eq    | missing                                                               |
| command [dfr drop-duplicates] with parameter [maintain] is missing in eq  | missing                                                               |
| command [dfr select] with parameter [rows] is missing in eq               | `select` renamed to `get`                                             |
| command [dfr select] with parameter [rest] is missing in eq               | `select` renamed to `get`                                             |
| command [dfr last] exists but parameter [n_rows] is missing in eq         | `n_rows` renamed to `rows`                                            |
| command [dfr melt] exists but parameter [value_name] is missing in eq     | `value_name` renamed to `value-name`                                  |
| command [dfr melt] exists but parameter [variable_name] is missing in eq  | `variable_name` renamed to `variable-name`                            |
| command [dfr open] exists but parameter [no_header] is missing in eq      | `no_header` reamed to `no-header`                                     |
| command [dfr open] exists but parameter [infer_schema] is missing in eq   | `infer_schema` renamed to `infer-schema`                              |
| command [dfr open] exists but parameter [skip_rows] is missing in eq      | `skip_rows` renamed to `skip-rows`                                    |
| command [dfr pivot] exists but parameter [pivot column] is missing in eq  | `pivot column` renamed to `pivot-column`                              |
| command [dfr pivot] exists but parameter [value column] is missing in eq  | `value column` renamed to `value-column`                              |
| command [dfr sample] exists but parameter [n_rows] is missing in eq       | `n_rows` renamed to `n-rows`                                          |
| command [dfr unique] with parameter [period] is missing in eq             | missing                                                               |
| command [dfr show] with parameter [tail] is missing in eq                 | `show` renamed to `to-nu`                                             |
| command [dfr show] with parameter [n_rows] is missing in eq               | `show` renamed to `to-nu`                                             |
| command [dfr replace] exists but parameter [length] is missing in eq      | missing                                                               |
| command [dfr replace] exists but parameter [start] is missing in eq       | missing                                                               |
| command [dfr to-csv] exists but parameter [no_header] is missing in eq    | `no_header` renamed to `no-header`                                    |
| command [dfr where] with parameter [condition] is missing in eq           | missing                                                               |
| command [date format] exists but parameter [format] is missing in eq      | `format` renamed to `format string` (\* space in param name)          |
| command [date format] exists but parameter [table] is missing in eq       | missing                                                               |
| command [date humanize] with parameter [table] is missing in eq           | missing                                                               |
| command [def] exists but parameter [name] is missing in eq                | `name` renamed to `def_name`                                          |
| command [default] with parameter [column name] is missing in eq           | missing                                                               |
| command [default] with parameter [column value] is missing in eq          | missing                                                               |
| command [detect columns] with parameter [no_headers] is missing in eq     | missing                                                               |
| command [detect columns] with parameter [skip] is missing in eq           | missing                                                               |
| command [drop nth] exists but parameter [row number] is missing in eq     | `row number` renamed to `rest`                                        |
| command [du] with parameter [path] is missing in eq                       | missing                                                               |
| command [du] with parameter [min-size] is missing in eq                   | missing                                                               |
| command [du] with parameter [all] is missing in eq                        | missing                                                               |
| command [du] with parameter [deref] is missing in eq                      | missing                                                               |
| command [du] with parameter [exclude] is missing in eq                    | missing                                                               |
| command [du] with parameter [max-depth] is missing in eq                  | missing                                                               |
| command [each group] with parameter [group_size] is missing in eq         | missing                                                               |
| command [each group] with parameter [block] is missing in eq              | missing                                                               |
| command [each window] with parameter [window_size] is missing in eq       | missing                                                               |
| command [each window] with parameter [block] is missing in eq             | missing                                                               |
| command [each window] with parameter [stride] is missing in eq            | missing                                                               |
| command [empty?] with parameter [rest] is missing in eq                   | `empty?` named `empty` in `$scope.commands.signature` - (\* bug)      |
| command [empty?] with parameter [block] is missing in eq                  | `empty?` named `empty` in `$scope.commands.signature` - (\* bug)      |
| command [enter] exists but parameter [location] is missing in eq          | `location` renamed `path`                                             |
| command [enter] exists but parameter [encoding] is missing in eq          | missing - (\* may not be needed without value shells)                 |
| command [exec] with parameter [command] is missing in eq                  | missing                                                               |
| command [exec] with parameter [rest] is missing in eq                     | missing                                                               |
| command [exit] exists but parameter [code] is missing in eq               | `code` renamed to `exit-code`                                         |
| command [find] with parameter [rest] is missing in eq                     | missing                                                               |
| command [for] exists but parameter [var] is missing in eq                 | `var` renamed to `var_name`                                           |
| command [for] exists but parameter [in] is missing in eq                  | `in` is not a parameter in engine-q                                   |
| command [for] exists but parameter [value] is missing in eq               | `value` renamed to `range`                                            |
| command [format filesize] with parameter [field] is missing in eq         | missing                                                               |
| command [format filesize] with parameter [format value] is missing in eq  | missing                                                               |
| command [from sqlite] with parameter [tables] is missing in eq            | missing                                                               |
| command [from xlsx] exists but parameter [noheaders] is missing in eq     | missing                                                               |
| command [g] exists but parameter [index] is missing in eq                 | `index` renamed to `shell-number`                                     |
| command [get] exists but parameter [rest] is missing in eq                | missing                                                               |
| command [group-by] with parameter [grouper] is missing in eq              | missing                                                               |
| command [group-by date] with parameter [column_name] is missing in eq     | missing                                                               |
| command [group-by date] with parameter [format] is missing in eq          | missing                                                               |
| command [hash] with parameter [rest] is missing in eq                     | missing                                                               |
| command [hash base64] with parameter [rest] is missing in eq              | missing                                                               |
| command [hash base64] with parameter [decode] is missing in eq            | missing                                                               |
| command [hash base64] with parameter [character_set] is missing in eq     | missing                                                               |
| command [hash base64] with parameter [encode] is missing in eq            | missing                                                               |
| command [histogram] with parameter [rest] is missing in eq                | missing                                                               |
| command [histogram] with parameter [use] is missing in eq                 | missing                                                               |
| command [if] exists but parameter [condition] is missing in eq            | `condition` renamed to `cond`                                         |
| command [if] exists but parameter [then_case] is missing in eq            | `then_case` renamed to `then_block`                                   |
| command [if] exists but parameter [else_case] is missing in eq            | `else_case` renmaed to `else_expression`                              |
| command [inc] exists but parameter [rest] is missing in eq                | missing                                                               |
| command [insert] with parameter [column] is missing in eq                 | `insert` command replace with `update` comand that inserts if missing |
| command [insert] with parameter [value] is missing in eq                  | `insert` command replace with `update` comand that inserts if missing |
| command [into column-path] with parameter [rest] is missing in eq         | missing                                                               |
| command [into path] with parameter [rest] is missing in eq                | missing - (\* not sure if needed now)                                 |
| command [keep] exists but parameter [rows] is missing in eq               | `rows` replaced with `n`                                              |
| command [keep until] exists but parameter [condition] is missing in eq    | `condition` replaced with `predicate`                                 |
| command [keep while] exists but parameter [condition] is missing in eq    | `condition` replaced with `predicate`                                 |
| command [let] exists but parameter [name] is missing in eq                | `name` replaced with `var_name`                                       |
| command [let] exists but parameter [equals] is missing in eq              | `equals` is not a parameter in engine-q                               |
| command [let] exists but parameter [expr] is missing in eq                | `expr` replaced with `initial_value`                                  |
| command [let-env] exists but parameter [name] is missing in eq            | `name` replaced with `var_name`                                       |
| command [let-env] exists but parameter [equals] is missing in eq          | `equals` is not a parameter in engine-q                               |
| command [let-env] exists but parameter [expr] is missing in eq            | `expr` replaced with `initial_value`                                  |
| command [load-env] with parameter [environ] is missing in eq              | missing                                                               |
| command [ls] exists but parameter [path] is missing in eq                 | `path` replaced with `pattern`                                        |
| command [ls] exists but parameter [du] is missing in eq                   | missing                                                               |
| command [match] with parameter [member] is missing in eq                  | missing                                                               |
| command [match] with parameter [regex] is missing in eq                   | missing                                                               |
| command [match] with parameter [invert] is missing in eq                  | missing                                                               |
| command [match] with parameter [insensitive] is missing in eq             | missing                                                               |
| command [match] with parameter [multiline] is missing in eq               | missing                                                               |
| command [match] with parameter [dotall] is missing in eq                  | missing                                                               |
| command [merge] with parameter [block] is missing in eq                   | missing                                                               |
| command [move] with parameter [rest] is missing in eq                     | missing                                                               |
| command [move] with parameter [before] is missing in eq                   | missing                                                               |
| command [move] with parameter [after] is missing in eq                    | missing                                                               |
| command [nth] exists but parameter [row number] is missing in eq          | `row number` replaced with `rest`                                     |
| command [nu plugin] with parameter [load] is missing in eq                | missing                                                               |
| command [open] exists but parameter [path] is missing in eq               | `path` replaced with `filename`                                       |
| command [open] exists but parameter [encoding] is missing in eq           | moved `encoding` to `decode` command                                  |
| command [pathvar] with parameter [var] is missing in eq                   | missing                                                               |
| command [pathvar add] with parameter [path] is missing in eq              | missing                                                               |
| command [pathvar add] with parameter [var] is missing in eq               | missing                                                               |
| command [pathvar append] with parameter [path] is missing in eq           | missing                                                               |
| command [pathvar append] with parameter [var] is missing in eq            | missing                                                               |
| command [pathvar remove] with parameter [index] is missing in eq          | missing                                                               |
| command [pathvar remove] with parameter [var] is missing in eq            | missing                                                               |
| command [pathvar reset] with parameter [var] is missing in eq             | missing                                                               |
| command [pathvar save] with parameter [var] is missing in eq              | missing                                                               |
| command [pivot] with parameter [rest] is missing in eq                    | missing                                                               |
| command [pivot] with parameter [ignore-titles] is missing in eq           | missing                                                               |
| command [pivot] with parameter [header-row] is missing in eq              | missing                                                               |
| command [post] with parameter [path] is missing in eq                     | missing                                                               |
| command [post] with parameter [body] is missing in eq                     | missing                                                               |
| command [post] with parameter [raw] is missing in eq                      | missing                                                               |
| command [post] with parameter [user] is missing in eq                     | missing                                                               |
| command [post] with parameter [password] is missing in eq                 | missing                                                               |
| command [post] with parameter [content-type] is missing in eq             | missing                                                               |
| command [post] with parameter [content-length] is missing in eq           | missing                                                               |
| command [prepend] exists but parameter [row value] is missing in eq       | `row value` renamed to `row`                                          |
| command [query json] with parameter [query] is missing in eq              | missing                                                               |
| command [rename] with parameter [column_name] is missing in eq            | missing                                                               |
| command [rename] with parameter [rest] is missing in eq                   | missing                                                               |
| command [roll] with parameter [by] is missing in eq                       | missing                                                               |
| command [roll column] with parameter [by] is missing in eq                | missing                                                               |
| command [roll column] with parameter [cells-only] is missing in eq        | missing                                                               |
| command [roll column] with parameter [opposite] is missing in eq          | missing                                                               |
| command [roll up] with parameter [by] is missing in eq                    | missing                                                               |
| command [rotate] with parameter [rest] is missing in eq                   | missing                                                               |
| command [rotate counter-clockwise] with parameter [rest] is missing in eq | missing                                                               |
| command [s3] with parameter [RESOURCE] is missing in eq                   | missing                                                               |
| command [s3] with parameter [raw] is missing in eq                        | missing                                                               |
| command [s3] with parameter [endpoint] is missing in eq                   | missing                                                               |
| command [s3] with parameter [access_key] is missing in eq                 | missing                                                               |
| command [s3] with parameter [secret_key] is missing in eq                 | missing                                                               |
| command [s3] with parameter [region] is missing in eq                     | missing                                                               |
| command [save] with parameter [path] is missing in eq                     | missing                                                               |
| command [save] with parameter [append] is missing in eq                   | missing                                                               |
| command [save] with parameter [raw] is missing in eq                      | missing                                                               |
| command [select] exists but parameter [columns] is missing in eq          | `columns` renamed to `rest`                                           |
| command [selector] with parameter [inspect] is missing in eq              | missing                                                               |
| command [selector] with parameter [query] is missing in eq                | missing                                                               |
| command [selector] with parameter [as_html] is missing in eq              | missing                                                               |
| command [selector] with parameter [attribute] is missing in eq            | missing                                                               |
| command [selector] with parameter [as_table] is missing in eq             | missing                                                               |
| command [seq] with parameter [rest] is missing in eq                      | missing                                                               |
| command [seq] with parameter [widths] is missing in eq                    | missing                                                               |
| command [seq] with parameter [separator] is missing in eq                 | missing                                                               |
| command [seq] with parameter [terminator] is missing in eq                | missing                                                               |
| command [seq date] with parameter [reverse] is missing in eq              | missing                                                               |
| command [seq date] with parameter [separator] is missing in eq            | missing                                                               |
| command [seq date] with parameter [output-format] is missing in eq        | missing                                                               |
| command [seq date] with parameter [input-format] is missing in eq         | missing                                                               |
| command [seq date] with parameter [begin-date] is missing in eq           | missing                                                               |
| command [seq date] with parameter [end-date] is missing in eq             | missing                                                               |
| command [seq date] with parameter [increment] is missing in eq            | missing                                                               |
| command [seq date] with parameter [days] is missing in eq                 | missing                                                               |
| command [skip] exists but parameter [rows] is missing in eq               | `rows` renamed to `n`                                                 |
| command [skip until] exists but parameter [condition] is missing in eq    | `condition` renamed to `predicate`                                    |
| command [skip while] exists but parameter [condition] is missing in eq    | `condition` renamed to `predicate`                                    |
| command [sort-by] with parameter [rest] is missing in eq                  | missing                                                               |
| command [sort-by] with parameter [reverse] is missing in eq               | missing                                                               |
| command [sort-by] with parameter [insensitive] is missing in eq           | missing                                                               |
| command [split-by] with parameter [column_name] is missing in eq          | missing                                                               |
| command [start] with parameter [rest] is missing in eq                    | missing                                                               |
| command [start] with parameter [application] is missing in eq             | missing                                                               |
| command [str] with parameter [rest] is missing in eq                      | missing                                                               |
| command [str to-datetime] with parameter [rest] is missing in eq          | command replaced with `into datetime`                                 |
| command [str to-datetime] with parameter [format] is missing in eq        | command replaced with `into datetime`                                 |
| command [str to-datetime] with parameter [timezone] is missing in eq      | command replaced with `into datetime`                                 |
| command [str to-datetime] with parameter [offset] is missing in eq        | command replaced with `into datetime`                                 |
| command [str to-decimal] with parameter [rest] is missing in eq           | command replaced with `into decimal`                                  |
| command [str to-int] with parameter [rest] is missing in eq               | command replaced with `into int`                                      |
| command [str to-int] with parameter [radix] is missing in eq              | command replaced with `into int`                                      |
| command [term size] with parameter [tall] is missing in eq                | missing                                                               |
| command [term size] with parameter [wide] is missing in eq                | missing                                                               |
| command [to json] exists but parameter [pretty] is missing in eq          | `pretty` missing because it defaults to pretty                        |
| command [tutor] with parameter [search] is missing in eq                  | missing                                                               |
| command [tutor] with parameter [find] is missing in eq                    | missing                                                               |
| command [unalias] with parameter [name] is missing in eq                  | missing - (\* replaced with `hide`?)                                  |
| command [unlet-env] with parameter [name] is missing in eq                | missing - (\* replaced with `hide`?)                                  |
| command [update cells] with parameter [block] is missing in eq            | missing                                                               |
| command [update cells] with parameter [columns] is missing in eq          | missing                                                               |
| command [where] exists but parameter [condition] is missing in eq         | `condition` replaced with `cond`                                      |
| command [which] with parameter [application] is missing in eq             | missing                                                               |
| command [which] with parameter [rest] is missing in eq                    | missing                                                               |
| command [which] with parameter [all] is missing in eq                     | missing                                                               |
| command [wrap] exists but parameter [column] is missing in eq             | `column` replaced with `name`                                         |
| command [xpath] with parameter [query] is missing in eq                   | missing                                                               |
| command [zip] exists but parameter [block] is missing in eq               | `block` replaced with `other`                                         |

**Comment by kubouch** [comment]
TIL zip is already ported

**Comment by efx** [comment]
I will try porting `find`.

**Comment by lukexor** [comment]
Also add that `starship` works but not out of the box with the default `line_break` module enabled. See #575

Work-around:
```
let-env PROMPT_COMMAND = { starship prompt | decode utf8 | str find-replace -a (char newline) (char crlf) }
```

**Comment by eggcaker** [comment]
I'm not sure I can do, but I  want to try to learn more with just port a simple command  , like du ?

**Comment by fdncred** [comment]
> I'm not sure I can do, but I want to try to learn more with just port a simple command , like du ?

go for it. just copy it from nushell and try to change the primitive types to engine-q types. This issue has some tips at the bottom. https://github.com/nushell/engine-q/issues/242

**Comment by eggcaker** [comment]
@fdncred did you add my name to the du command already, could you remove for now, seems lot of thing need to learn about nushell and rust .

**Comment by fdncred** [comment]
> @fdncred did you add my name to the du command already, could you remove for now, seems lot of thing need to learn about nushell and rust .

sure. no worries.
